# Generated by Django 4.1.7 on 2023-04-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module_Code', models.CharField(max_length=100)),
                ('Part', models.CharField(max_length=200)),
                ('Module_name', models.CharField(max_length=200)),
                ('Manditory', models.BooleanField(default=False)),
                ('Followed_by', models.CharField(max_length=100)),
                ('Precursed_by', models.CharField(max_length=100)),
                ('Technical_skill', models.IntegerField(default=0)),
                ('Communication_skill', models.IntegerField(default=0)),
                ('Mathmatical_skill', models.IntegerField(default=0)),
                ('Coding_skill', models.IntegerField(default=0)),
                ('Project_manag_skill', models.IntegerField(default=0)),
                ('Professional_dev_skill', models.IntegerField(default=0)),
            ],
        ),
    ]
