# Generated by Django 4.1.7 on 2023-04-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_moduleinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleinfo',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moduleinfo',
            name='Semester',
            field=models.IntegerField(default=0),
        ),
    ]
