# Generated by Django 4.1.7 on 2023-04-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_moduleinfo_completed_moduleinfo_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleLinking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Followed_by', models.CharField(max_length=100)),
                ('Precursed_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserModuleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=100)),
                ('User_age', models.IntegerField(default=0)),
                ('User_course', models.CharField(max_length=100)),
                ('User_current_part', models.CharField(max_length=100)),
                ('User_Technical_skill', models.IntegerField(default=0)),
                ('User_Communication_skill', models.IntegerField(default=0)),
                ('User_Mathmatical_skill', models.IntegerField(default=0)),
                ('User_Coding_skill', models.IntegerField(default=0)),
                ('User_Project_manag_skill', models.IntegerField(default=0)),
                ('User_Professional_dev_skill', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='moduleinfo',
            old_name='Coding_skill',
            new_name='Module_Coding_skill',
        ),
        migrations.RenameField(
            model_name='moduleinfo',
            old_name='Communication_skill',
            new_name='Module_Communication_skill',
        ),
        migrations.RenameField(
            model_name='moduleinfo',
            old_name='Completed',
            new_name='Module_Completed_by_user',
        ),
        migrations.RenameField(
            model_name='moduleinfo',
            old_name='Manditory',
            new_name='Module_Manditory',
        ),
        migrations.RenameField(
            model_name='moduleinfo',
            old_name='Mathmatical_skill',
            new_name='Module_Mathmatical_skill',
        ),
        migrations.RenameField(
            model_name='moduleinfo',
            old_name='Part',
            new_name='Module_Part',
        ),
        migrations.RenameField(
            model_name='moduleinfo',
            old_name='Professional_dev_skill',
            new_name='Module_Professional_dev_skill',
        ),
        migrations.RenameField(
            model_name='moduleinfo',
            old_name='Project_manag_skill',
            new_name='Module_Project_manag_skill',
        ),
        migrations.RenameField(
            model_name='moduleinfo',
            old_name='Semester',
            new_name='Module_Semester',
        ),
        migrations.RenameField(
            model_name='moduleinfo',
            old_name='Technical_skill',
            new_name='Module_Technical_skill',
        ),
        migrations.RemoveField(
            model_name='moduleinfo',
            name='Followed_by',
        ),
        migrations.RemoveField(
            model_name='moduleinfo',
            name='Precursed_by',
        ),
    ]
