# Generated by Django 4.1.7 on 2023-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_modulelinking_usermoduleinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulelinking',
            name='Link_Module_code',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
