# Generated by Django 4.1.7 on 2023-04-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_modulelinking_link_module_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
