# Generated by Django 4.1.7 on 2023-04-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleinfo',
            name='User_student_id',
            field=models.CharField(default='N/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermoduleinfo',
            name='User_student_password',
            field=models.CharField(default='N/a', max_length=100),
            preserve_default=False,
        ),
    ]
