# Generated by Django 4.1.7 on 2023-04-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_usermoduleinfo_user_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoduleinfo',
            name='User_student_id',
            field=models.CharField(default='N/a', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermoduleinfo',
            name='User_student_password',
            field=models.CharField(default='N/a', max_length=100),
        ),
    ]
